[tool.hatch]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydantic-core-stubs"
version = "0.1.0"

[tool.hatch.build.targets.sdist]
packages = ["pydantic_core-stubs"]
[tool.hatch.build.targets.wheel]
packages = ["pydantic_core-stubs"]
